on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: miniprojectacr.azurecr.io
        username: ${{ secrets.acr_miniprojectacr_username }}
        password: ${{ secrets.acr_miniprojectacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/board-app" -f  "board-app/Dockerfile" -t miniprojectacr.azurecr.io/miniprojectaks:${{ github.sha }} --label dockerfile-path=board-app/Dockerfile
        docker push miniprojectacr.azurecr.io/miniprojectaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_miniprojectaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep miniproject-app | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace miniproject-app`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: miniproject-app
        container-registry-url: miniprojectacr.azurecr.io
        container-registry-username: ${{ secrets.acr_miniprojectacr_username }}
        container-registry-password: ${{ secrets.acr_miniprojectacr_password }}
        secret-name: miniprojectadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: miniproject-app
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          miniprojectacr.azurecr.io/miniprojectaks:${{ github.sha }}
        imagepullsecrets: |
          miniprojectadockerauth
